### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Radiergummi** [Baldinof/roadrunner-bundle#1]
Hey there, I found this project highly useful, so I created a skeleton Docker project with the roadrunner bundle installed and configured out of the box.  
You can find it here: https://github.com/Radiergummi/roadrunner-symfony-skeleton

Just wanted to let you know.

**Comment by Baldinof** [comment]
Nice! Glad to see that it's helpful to someone :)

I think I will backport the [documented config file](https://github.com/Radiergummi/roadrunner-symfony-skeleton/blob/master/config/packages/baldinof_road_runner.yaml) to the Flex recipe.
