### ISSUE TITLE
3.0.1 patch version dropped support for symfony ^6.0

### ISSUE THREAD

**Issue by rmikalkenas** [Baldinof/roadrunner-bundle#129]
What's the reason that patch version (3.0.1) completely dropped support for symfony ^6.0?

6.4 and 7.0 is not yet released, therefore 3.0.1 is basically unusable :man_shrugging: 

IMO, such changes should result to major version, since it's a breaking change

**Comment by Baldinof** [comment]
Hello,

Sorry, I reviewed a PR too quickly. I released 3.0.2 to allow back ^6.0.

This is note a BC, composer would simply skip this version if it is not compatible with your project.

**Comment by rmikalkenas** [comment]
Thanks for such a fast reaction! :pray:
