### ISSUE TITLE
Event dispatcher doesn't reset automatically after next request

### ISSUE THREAD

**Issue by dmitryuk** [Baldinof/roadrunner-bundle#135]
Example code
```
// some business logic here...
        $this->eventDispatcher->addListener(
            KernelEvents::TERMINATE,
            fn () => sendEmailForExample()
        );
```

Next request will cause n+1 call of `sendEmailForExample`

I need to reset EventDispatcher manually with removing these listeners

**Comment by Baldinof** [comment]
No, it is not resetted unless a [kernel reboot happens](https://github.com/Baldinof/roadrunner-bundle#kernel-reboots).

So if you call `addListener()` within your code (in a controller), listeners will stack ups.

If you want to do stuff in the background **I would recommend to use Symfony Messenger**, or write a custom service that listen `KernelEvents::TERMINATE` and empty the tasks list right after.

Something like

```php
class RunAfterRequest
{
    private array $tasks = [];

    public function add(\Closure $callback): void
    {
        $this->tasks[] = $callback;
    }

    #[AsEventListener(KernelEvents::TERMINATE)]
    public function run()
    {
        while (count($this->tasks) > 0) {
            $task = array_shift($this->tasks);
            $task();
        }
    }
}
```

Then you can inject the `RunAfterRequest` service and call `add()` to add a task to be run after the kernel terminate. 

Still, I think **Messenger is the best option**
