### ISSUE TITLE
nginx and subdomains

### ISSUE THREAD

**Issue by zmitic** [Baldinof/roadrunner-bundle#14]
Sorry if there is explanation somewhere but couldn't find it even on RR repo.

The issue is that I have an application with URL like 

```
http://client_1.something.flex
http://client_2.something.flex

// for super-admin
http://something.flex
```

Something like this:

<details>
  <summary>Click to expand nginx config</summary>

```
server {
    listen *:80;
    server_name *.something.flex something.flex;
    root /home/zmitic/PhpstormProjects/something/public;
    location / {
        try_files $uri /index.php$is_args$args;
    }
    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param BASE_URL something.flex;
	proxy_ignore_client_abort on;
    }
}
```
</details>

Subdomain is used to determine client and apply Doctrine filters when needed.

Is it possible to do the same with RR and your bundle and have URL like: ``http://client_1.something.rr``?

Production uses HTTPS set by another person, that might be problem as well but I do want to use RR on real project. Current nginx setup takes about 70-90ms, it would be nice to cut 30-40ms.

Thanks.

**Comment by zmitic** [comment]
Never mind, proxy pass did the job.

**Comment by Baldinof** [comment]
Hi!

I'm glad you found a solution, thank you for your interest in this package!

Did you get the expected performance boost?

**Comment by zmitic** [comment]
@Baldinof Well... it is faster but honestly, not as much as I expected.

I still have about 70-100 (from 200) initialization time which I though will be gone completely. For that reason, I bought Blackfire and I will profile which part exactly is draining resources.

But for the bundle itself; yep, very **very** happy. Finally one that solved session problems; Swoole, RR, PHP-PM... each gave me tons of problems. Even upload works :smile: 

I will further test it and create issue to inform you about progress, especially comparison with regular FPM setup.

**Comment by zmitic** [comment]
The only real problem is that memory keeps increasing in dev, easily reaching 50MB+. Luckily I can set restart but surely would be nicer not to happy scary looking warning in profiler.

**Comment by Baldinof** [comment]
Nice! Thank you for the feedback :)
