### ISSUE TITLE
Invalid SentryMiddleware configuration

### ISSUE THREAD

**Issue by bua89** [Baldinof/roadrunner-bundle#34]
Hello :)

First of all, great job with this bundle. Kudos from me :)

I receive an issue with newest version here: https://github.com/Baldinof/roadrunner-bundle/commit/511bf8a045af9a98a5c7eda89785405fa24c80f0#diff-04a038ad261e1cf28fe6ed43ee16fda9a9d174ae8d35b0b7c673bda6ce005e69R119
```php
            $container
                ->register(SentryMiddleware::class)
                ->addArgument(HubInterface::class);
```

It seams that you need to change `HubInterface::class` to `new Reference(HubInterface::class)`.

**Comment by Baldinof** [comment]
Hi, thanks for the feedback :)

I noticed this while working on RoadRunner v2 integration, but forgot to backport the fix on master 🤦 

It's fixed and released in 1.5.3!
