### ISSUE TITLE
Bundle not load correct .env file

### ISSUE THREAD

**Issue by asterd** [Baldinof/roadrunner-bundle#36]
Hi, 
thanks a lot for this beautiful package, but I have an annoying issue: even if I run rr in dev, with .rr.dev.yaml, setting APP_ENV=dev or any other possible option, symfony loads only .env file ignoring any other .env.* file (.env.local, .env.dev.local, .env.prod, etc...). I've also tried with composer dump-env dev but nothing.. it reads ONLY .env file.

Can you help me please?
Thanks a lot.

**Comment by Baldinof** [comment]
Hi thanks for the feedback :) 

I am not sure if it's a problem from this bundle, can you show me the output of `composer show`?

**Comment by asterd** [comment]
adyen/php-api-library                7.1.0              A PHP client library for accessing Adyen APIs
baldinof/roadrunner-bundle           2.0.0              A RoadRunner worker as a Symfony Bundle
bcspa/entityrepository               v1.0.20            Extesion of the nealis/entity-repository with some additional features and a more ...
bcspa/exceptions                     v1.0.5             Shared exception management lib
bcspa/ibmi-dbal                      v1.0.8             Fork of alanseiden/doctrine-dbal-ibmi with edge unmerged commits
bcspa/ibmi-toolkit                   v1.2.2             Wrapper for easily access IBMI RPG resources using PHPToolkit
bcspa/ibmitoolkit                    v1.8.6             PHP frontend to XMLSERVICE for IBM i development.
bcspa/logger                         1.0.2              Logging support lib
bcspa/security                       v1.0.11            Security library to add support to secure (with JTW) api calls
bcspa/utils                          v1.1.3             Collection of useful classes for the bcspa-backend project. This package contains ...
cloudinary/cloudinary_php            2.1.1              Cloudinary PHP SDK
colinmollenhour/credis               v1.12.1            Credis is a lightweight interface to the Redis key-value store which wraps the php...
composer/package-versions-deprecated 1.11.99.1          Composer plugin that provides efficient querying for installed package versions (n...
composer/semver                      3.2.4              Semver library that offers utilities, version constraint parsing and validation.
doctrine/annotations                 1.12.1             Docblock Annotations Parser
doctrine/cache                       1.10.2             PHP Doctrine Cache library is a popular cache implementation that supports many di...
doctrine/collections                 1.6.7              PHP Doctrine Collections library that adds additional functionality on top of PHP ...
doctrine/common                      2.13.3             PHP Doctrine Common project is a library that provides additional functionality th...
doctrine/dbal                        2.13.0             Powerful PHP database abstraction layer (DBAL) with many features for database sch...
doctrine/deprecations                v0.5.3             A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with opt...
doctrine/doctrine-bundle             2.3.0              Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle  2.2.2              Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.1              The Doctrine Event Manager is a simple PHP event system that was built to be used ...
doctrine/inflector                   1.4.3              PHP Doctrine Inflector is a small library that can perform string manipulations wi...
doctrine/instantiator                1.4.0              A small, lightweight utility to instantiate objects in PHP without invoking their ...
doctrine/lexer                       1.2.1              PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent ...
doctrine/migrations                  2.3.3              PHP Doctrine Migrations project offer additional functionality on top of the datab...
doctrine/orm                         2.7.5              Object-Relational-Mapper for PHP
doctrine/persistence                 1.3.8              The Doctrine Persistence project is a set of shared interfaces and functionality t...
doctrine/reflection                  1.2.2              The Doctrine Reflection project is a simple library used by the various Doctrine p...
doctrine/sql-formatter               1.1.1              a PHP SQL highlighting library
dompdf/dompdf                        v0.8.6             DOMPDF is a CSS 2.1 compliant HTML to PDF converter
egulias/email-validator              3.1.0              A library for validating emails against several RFCs
ezyang/htmlpurifier                  v4.13.0            Standards compliant HTML filter written in PHP
firebase/php-jwt                     v5.2.1             A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform...
friendsofphp/proxy-manager-lts       v1.0.3             Adding support for a wider range of PHP versions to ocramius/proxy-manager
guzzlehttp/guzzle                    7.3.0              Guzzle is a PHP HTTP client library
guzzlehttp/promises                  1.4.1              Guzzle promises library
guzzlehttp/psr7                      1.8.1              PSR-7 message implementation that also provides common utility methods
laminas/laminas-code                 4.1.0              Extensions to the PHP Reflection API, static code scanning, and code generation
laminas/laminas-eventmanager         3.3.1              Trigger and listen to events within a PHP application
laminas/laminas-zendframework-bridge 1.2.0              Alias legacy ZF class names to Laminas Project equivalents.
lorenzo/pinky                        1.0.5              A Foundation for Emails (Inky) template transpiler
maennchen/zipstream-php              2.1.0              ZipStream is a library for dynamically streaming dynamic zip files from PHP withou...
markbaker/complex                    2.0.0              PHP Class for working with complex numbers
markbaker/matrix                     2.1.2              PHP Class for working with matrices
monolog/monolog                      2.2.0              Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/php-enum                     1.8.0              PHP Enum implementation
nelmio/cors-bundle                   2.1.0              Adds CORS (Cross-Origin Resource Sharing) headers support in your Symfony application
nikic/php-parser                     v4.10.4            A PHP parser written in PHP
nyholm/psr7                          1.4.0              A fast PHP7 implementation of PSR-7
phenx/php-font-lib                   0.5.2              A library to read, parse, export and make subsets of different types of font files.
phenx/php-svg-lib                    v0.3.3             A library to read, parse and export to PDF SVG files.
php-http/message-factory             v1.0.2             Factory interfaces for PSR-7 HTTP Message
phpoffice/phpspreadsheet             1.17.1             PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet...
phpstan/phpstan                      0.12.82            PHPStan - PHP Static Analysis Tool
picqer/php-barcode-generator         v2.2.0             An easy to use, non-bloated, barcode generator in PHP. Creates SVG, PNG, JPG and H...
predis/predis                        v1.1.6             Flexible and feature-complete Redis client for PHP and HHVM
psr/cache                            1.0.1              Common interface for caching libraries
psr/container                        1.1.1              Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                 1.0.0              Standard interfaces for event handling.
psr/http-client                      1.0.1              Common interface for HTTP clients
psr/http-factory                     1.0.1              Common interfaces for PSR-7 HTTP message factories
psr/http-message                     1.0.1              Common interface for HTTP messages
psr/log                              1.1.3              Common interface for logging libraries
psr/simple-cache                     1.0.1              Common interfaces for simple caching
ralouphie/getallheaders              3.0.3              A polyfill for getallheaders.
resque/php-resque                    v1.3.6             Redis backed library for creating background jobs and processing them later. Based...
roave/security-advisories            dev-master 0a55b3e Prevents installation of composer packages with known security vulnerabilities: no...
sabberworm/php-css-parser            8.3.1              Parser for CSS Files written in PHP
sensio/framework-extra-bundle        v5.6.1             This bundle provides a way to configure your controllers with annotations
shrikeh/teapot                       v2.3.1             PHP HTTP Response Status library
spatie/image-optimizer               1.3.2              Easily optimize images using PHP
spiral/goridge                       v3.0.1             High-performance PHP-to-Golang RPC bridge
spiral/roadrunner                    v2.0.4             RoadRunner: High-performance PHP application server, load-balancer and process man...
spiral/roadrunner-cli                v2.0.2             RoadRunner: Command Line Interface
spiral/roadrunner-http               v2.0.0             RoadRunner: HTTP and PSR-7 worker
spiral/roadrunner-worker             v2.0.3             RoadRunner: PHP worker
symfony-bundles/redis-bundle         3.1.2              Symfony Redis Bundle
symfony/amqp-messenger               v5.2.4             Symfony AMQP extension Messenger Bridge
symfony/cache                        v5.2.6             Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts              v2.2.0             Generic abstractions related to caching
symfony/config                       v5.2.4             Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                      v5.2.6             Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                 v5.2.4             Converts CSS selectors to XPath expressions
symfony/debug-bundle                 v5.2.4             Provides a tight integration of the Symfony Debug component into the Symfony full-...
symfony/debug-pack                   v1.0.9             A debug pack for Symfony projects
symfony/dependency-injection         v5.2.6             Allows you to standardize and centralize the way objects are constructed in your a...
symfony/deprecation-contracts        v2.2.0             A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge              v5.2.0-RC2         Symfony Doctrine Bridge
symfony/doctrine-messenger           v5.2.5             Symfony Doctrine Messenger Bridge
symfony/dotenv                       v5.2.4             Registers environment variables from a .env file
symfony/error-handler                v5.2.6             Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher             v5.2.4             Provides tools that allow your application components to communicate with each oth...
symfony/event-dispatcher-contracts   v2.2.0             Generic abstractions related to dispatching event
symfony/expression-language          v5.2.4             Provides an engine that can compile and evaluate expressions
symfony/filesystem                   v5.2.6             Provides basic utilities for the filesystem
symfony/finder                       v5.2.4             Finds files and directories via an intuitive fluent interface
symfony/flex                         v1.12.2            Composer plugin for Symfony
symfony/framework-bundle             v5.2.6             Provides a tight integration between Symfony components and the Symfony full-stack...
symfony/http-client                  v5.2.6             Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts        v2.3.1             Generic abstractions related to HTTP clients
symfony/http-foundation              v5.2.4             Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                  v5.2.6             Provides a structured process for converting a Request into a Response
symfony/intl                         v5.2.4             Provides a PHP replacement layer for the C intl extension that includes additional...
symfony/lock                         v5.2.6             Creates and manages locks, a mechanism to provide exclusive access to a shared res...
symfony/mailer                       v5.2.6             Helps sending emails
symfony/maker-bundle                 v1.30.2            Symfony Maker helps you create empty commands, controllers, form classes, tests an...
symfony/mercure                      v0.4.1             Symfony Mercure Component
symfony/mercure-bundle               v0.2.6             Symfony MercureBundle
symfony/messenger                    v5.2.5             Helps applications send and receive messages to/from other applications or via mes...
symfony/mime                         v5.2.6             Allows manipulating MIME messages
symfony/monolog-bridge               v5.2.5             Provides integration for Monolog with various Symfony components
symfony/monolog-bundle               v3.7.0             Symfony MonologBundle
symfony/orm-pack                     v1.2.0             A pack for the Doctrine ORM
symfony/polyfill-intl-grapheme       v1.22.1            Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu            v1.22.1            Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn            v1.22.1            Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer     v1.22.1            Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-php73               v1.22.1            Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.22.1            Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                      v5.2.4             Executes commands in sub-processes
symfony/profiler-pack                v1.0.5             A pack for the Symfony web profiler
symfony/property-access              v5.2.4             Provides functions to read and write from/to an object or array using a simple str...
symfony/property-info                v5.2.4             Extracts information about PHP class' properties using metadata of popular sources
symfony/psr-http-message-bridge      v2.1.0             PSR HTTP message bridge
symfony/redis-messenger              v5.2.4             Symfony Redis extension Messenger Bridge
symfony/routing                      v5.2.6             Maps an HTTP request to a set of configuration variables
symfony/security-bundle              v5.2.6             Provides a tight integration of the Security component into the Symfony full-stack...
symfony/security-core                v5.2.6             Symfony Security Component - Core Library
symfony/security-csrf                v5.2.4             Symfony Security Component - CSRF Library
symfony/security-guard               v5.2.4             Symfony Security Component - Guard
symfony/security-http                v5.2.6             Symfony Security Component - HTTP Integration
symfony/serializer                   v5.2.4             Handles serializing and deserializing data structures, including object graphs, in...
symfony/service-contracts            v2.2.0             Generic abstractions related to writing services
symfony/stopwatch                    v5.2.4             Provides a way to profile code
symfony/string                       v5.2.6             Provides an object-oriented API to strings and deals with bytes, UTF-8 code points...
symfony/translation                  v5.2.6             Provides tools to internationalize your application
symfony/translation-contracts        v2.3.0             Generic abstractions related to translation
symfony/twig-bridge                  v5.2.6             Provides integration for Twig with various Symfony components
symfony/twig-bundle                  v5.2.4             Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                    v5.2.6             Provides tools to validate values
symfony/var-dumper                   v5.2.6             Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                 v5.2.4             Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-profiler-bundle          v5.2.6             Provides a development tool that gives detailed information about the execution of...
symfony/yaml                         v5.2.5             Loads and dumps YAML files
teapot/status-code                   v1.1.2             PHP HTTP Response Status code library
tijsverkoyen/css-to-inline-styles    2.2.3              CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTM...
twig/cssinliner-extra                v3.3.0             A Twig extension to allow inlining CSS
twig/extra-bundle                    v3.3.0             A Symfony bundle for extra Twig extensions
twig/inky-extra                      v3.3.0             A Twig extension for the inky email templating engine
twig/intl-extra                      v3.3.0             A Twig extension for Intl
twig/twig                            v3.3.0             Twig, the flexible, fast, and secure template language for PHP

**Comment by asterd** [comment]
maybe is not your bundle problem, but I've also try to set http env with APP_ENV = dev in rr.dev.yaml as documented in roadrunner official doc.. but nothing... this is very very strange

**Comment by Baldinof** [comment]
👍  it looks like it's a recent project, what is the content of `bin/console`? Did you change it?

**Comment by asterd** [comment]
nope.. I haven't touched it.. it is the same from long time.. and running on php-fpm works good.
Anyway the content is:

`
#!/usr/bin/env php
<?php

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\ErrorHandler\Debug;

// This will let the permissions be 0775
umask(0002);

if (false === in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    echo 'Warning: The console should be invoked via the CLI version of PHP, not the '.\PHP_SAPI.' SAPI'.\PHP_EOL;
}

set_time_limit(0);

require dirname(__DIR__).'/vendor/autoload.php';

if (!class_exists(Application::class)) {
    throw new RuntimeException('You need to add "symfony/framework-bundle" as a Composer dependency.');
}

$input = new ArgvInput();
if (null !== $env = $input->getParameterOption(['--env', '-e'], null, true)) {
    putenv('APP_ENV='.$_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = $env);
}

if ($input->hasParameterOption('--no-debug', true)) {
    putenv('APP_DEBUG='.$_SERVER['APP_DEBUG'] = $_ENV['APP_DEBUG'] = '0');
}

require dirname(__DIR__).'/config/bootstrap.php';

if ($_SERVER['APP_DEBUG']) {
    umask(0000);

    if (class_exists(Debug::class)) {
        Debug::enable();
    }
}

$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$application = new Application($kernel);
$application->run($input);
`

**Comment by Baldinof** [comment]
I see it's using a `config/bootstrap.php`, this file has been removed, see https://github.com/symfony/recipes/blob/master/symfony/console/5.1/bin/console

Can you try to update the console file?

Also do you have `APP_ENV` defined in you shell?

**Comment by asterd** [comment]
nothing to do.
I have updated the console file according to latest versione and set APP_ENV both with export and running rr in this way:
APP_ENV=dev bin/rr serve -c .rr.dev.yaml

nothing to do...

**Comment by asterd** [comment]
I've found! sorry to have annoyed you with this unuseful bug. In the very latest version of roadrunner (v2.0.4) they have added a dotenv support that now (as I can see) requires to rung the command in this way:
bin/rr serve -c .rr.dev.yaml --dotenv=. 

where . in my case is the root dir (where i run the command and where there are my .env.* files)
Sorry and thank you so much!
