### ISSUE TITLE
How to force https?

### ISSUE THREAD

**Issue by denisvmedia** [Baldinof/roadrunner-bundle#39]
In my local dev environment I use [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy). It allows running local virtual hosts with https support. And this bundle all works fine, except one thing: Symfony doesn't see connection protocol as `https`. If I manually force the following in `HttpFoundationWorker`:

```php
$server['HTTPS'] = 'on';
$server['SERVER_PORT'] = 443;
```

it starts working, but how can I do that in a proper manner? Otherwise all the generated links have `http` as a scheme.

P.S. I also debugged deeper and discovered that this happens because `$request->uri` contains `http` instead of `https`. But how to tell it to use https?

**Comment by Baldinof** [comment]
Hi!

I think you need to configure _trusted proxies_, see https://symfony.com/doc/current/deployment/proxies.html

If you are running the proxy locally, I guess you will need to trust `127.0.0.1`.

**Comment by denisvmedia** [comment]
Thank you. Unfortunately, it didn't help.

```bash
/var/www/html # php bin/console debug:config framework trusted_proxies

Current configuration for "framework.trusted_proxies"
=====================================================

127.0.0.1
/var/www/html # php bin/console debug:config framework trusted_headers

Current configuration for "framework.trusted_headers"
=====================================================

- x-forwarded-for
- x-forwarded-host
- x-forwarded-proto
- x-forwarded-port
```

**Comment by Baldinof** [comment]
Sorry to hear that :/

Can you provide a docker-compose example so that I can reproduce it?

**Comment by denisvmedia** [comment]
@Baldinof here is an example: https://github.com/denisvmedia/rr-problem-demo

Please note, although the project demonstrates the problem using local https certificates, the same applies to production, where we run using a similar configuration (HTTPS:443 nginx reverse proxy that proxies HTTP:80 connections to the internal infrastructure).

**Comment by Baldinof** [comment]
Thank you for the great reproducer! I will have a look in the weekend :)

**Comment by Baldinof** [comment]
I got it working by trusting the IP nginx received in the docker network (172.27.0.1 for me).

Can you try with this configuration?

```yaml
framework:
    trusted_proxies: '172.0.0.0/8'
    # trust *all* "X-Forwarded-*" headers
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']
```

For your production setup, you will have to trust your nginx IP as well.

**Comment by denisvmedia** [comment]
Yeah, it works (although I have another subnet). Thank you!

However, I feel something wrong there. I still have a feeling that it should be done on the side of RR. If it's done on their side, then any framework, any application will not have to do anything in addition. It's the same like defining `fastcgi_param HTTPS on` when using plain old php-fpm. In the end, it would cost much less effort when doing it in a single place.

**Comment by Baldinof** [comment]
Nice!

Note that Symfony allow to use `REMOTE_ADDR` as a `trusted_proxies` value, to trust all requests, but this is not handled yet in this bundle.

As I explained on the RR issue, I don't think this should be handled on the RR side as it's well handled by PHP frameworks and subject to security issues.

**Comment by denisvmedia** [comment]
I see, thank you for your efforts and help. I will close this issue.

**Comment by Baldinof** [comment]
Thank you for using this bundle :)

Do not hesitate to open other issues if needed!
