### ISSUE TITLE
Deploying an AMQP worker

### ISSUE THREAD

**Issue by mvaljento** [Baldinof/roadrunner-bundle#40]
My apologies if this is explained somewhere or if this is not the correct place to address this, but I recently started migrating my service to Roadrunner and I read through both Roadrunner and Roadrunner bundle instructions, but could not find an answer.

I've managed to get my API service running on Roadrunner using this bundle, but how can I run a custom command as a worker, in this case a Messanger consumer command like I have done with Supervisord in the past?

```
php bin/console messenger:consume

**Comment by Baldinof** [comment]
Hi, thanks for using this bundle :)

RoadRunner is used only as a HTTP server, if you need additional processes (AMQP workers for example) you need to start them in another way.

You can continue to use Supervisord to launch RoadRunner and your Messenger consumer.

**Comment by Baldinof** [comment]
It seems that you can now run side processes since RoadRunner 2.0.5 with the `service` plugin: https://roadrunner.dev/docs/beep-beep-service

**Comment by mvaljento** [comment]
> It seems that you can now run side processes since RoadRunner 2.0.5 with the `service` plugin: https://roadrunner.dev/docs/beep-beep-service

That seems to be exactly what I was looking for, thanks!
