### ISSUE TITLE
Support $_SERVER as in the spiral/roadrunner-http

### ISSUE THREAD

**Issue by real420og** [Baldinof/roadrunner-bundle#53]
Some projects (on symfony + roadrunner-bundle) depends on a third party library in which the $_SERVER['REQUEST_URI'] is called.

In the https://github.com/spiral/roadrunner-http/blob/master/src/PSR7Worker.php#L98 i saw the override of the $_SERVER by the result of the method

I see the value of this approach, but there are risks I might overlook. What do you think about it?

**Comment by Baldinof** [comment]
Hi!

As RoadRunner resets `$_SERVER` with the current request data, third party library should behave correctly.

**Comment by real420og** [comment]
REQUEST_URI which is generated in https://github.com/Baldinof/roadrunner-bundle/blob/2.x/src/RoadRunnerBridge/HttpFoundationWorker.php#L111

currently not available in $_SERVER

**Comment by Baldinof** [comment]
Sorry for the late response, this is now fixed in 2.2.0.

Thanks for the report :)
