### ISSUE TITLE
Connection Ping dbal deprecated

### ISSUE THREAD

**Issue by Fichtme** [Baldinof/roadrunner-bundle#54]
Hi, 

Im just using ur bundle for a couple of months, it works great in our old Symfony 4.4 project!

I just started creating a new project with your bundle, but stumbled against a deprecated issue with DBAL.

DoctrineORMMiddleware.php:50 $connection->ping() is deprecated (application crashing as a result of this). if its to check if the conneciton is alive we could do a simple select query right?

**Comment by Baldinof** [comment]
Hi!

Thank you for using this bundle :)

I will try to have a look!

**Comment by Fichtme** [comment]
Thnx!

If i can help in anyway just send me a message.

**Comment by Baldinof** [comment]
The fix is released in 2.1.1 :)
