### ISSUE TITLE
Working example with gRPC?

### ISSUE THREAD

**Issue by Bullace** [Baldinof/roadrunner-bundle#72]
Hey,

I'm having some issues getting gRPC to work. I keep running into the error below. I got the example from RoadRunner to work just fine, I added in Symfony 6 and your bundle, which also run but as soon as I add the gRPC settings to the yaml configuration I keep getting this error. If it rings any bells I'd like to hear but otherwise a working example would be fine also, thanks.

```roadrunner_1  | handle_serve_command: Serve error:
roadrunner_1  |         endure_start:
roadrunner_1  |         endure_serve_internal: Function call error:
roadrunner_1  |         endure_call_serve_fn: got initial serve error from the Vertex grpc.Plugin, stopping execution, error:
 grpc_plugin_serve: WorkerAllocate:
roadrunner_1  |         static_pool_allocate_workers:
roadrunner_1  |         goridge_frame_receive: CRC verification failed, bad header: 
roadrunner_1  | RoadRunner Bundle
roadrunner_1  | =================
roadrunner_1  | 
roadrunner_1  |  [```

**Comment by Baldinof** [comment]
Hi, thank you for trying this out :)

Can you show your RR config?

**Comment by Bullace** [comment]
I figured I should just upload the whole project, you can find it here https://github.com/Bullace/roadrunner-symfony-grpc-test

I'm not really into the whole PHP stuff myself, just helping out the backend team with figuring out how to move away from the monolithic stuff we're stuck in (so I'm not sure what I'm doing is really correct).
Anyway, I got the road runner grpc example working inside a docker container (which is broken now after messing with namespaces), added Symfony on top and then your bundle. Symfony runs but when I add the grpc section to the config it breaks.

**Comment by Baldinof** [comment]
Thank you, here's a working version of your repo https://github.com/Bullace/roadrunner-symfony-grpc-test/pull/1

I should add more doc on gRPC here 😅

**Comment by Bullace** [comment]
Wow, thank you so much!
