### ISSUE TITLE
Symfony stopped catching exceptions

### ISSUE THREAD

**Issue by WagnerPMC** [Baldinof/roadrunner-bundle#75]
Hello there,

I am using php 8.1.3, RR 2.8.2, RR-bundle 2.2.0
The problem is that the Symfony error handler has stopped catching \Error exceptions
Normal exceptions are intercepted in normal mode

To reproduce:
In any action: throw new \Error();

**Comment by Baldinof** [comment]
Hi!

You are right, symfony does not catch only catch `Exception` and let `Error` be handled by a registered error handler.

But in RR context, the throwable got caught [here](https://github.com/Baldinof/roadrunner-bundle/blob/2.x/src/Worker/Worker.php#L98) and is just sent to RR via `->error()`.

I guess we could also send a HTTP response containing the exception, if debug is enabled.

**Comment by Baldinof** [comment]
Can you try with the branch used to create #77 please?

**Comment by WagnerPMC** [comment]
@Baldinof yeah. It's cool now 🤗

**Comment by WagnerPMC** [comment]
@Baldinof
I think we also need to intercept Uncaught Error

**Comment by Baldinof** [comment]
The code is catching all type of errors (`Throwable`), it was just not rendering the error using the `ErrorHandler` if it was available.

**Comment by WagnerPMC** [comment]
I see that bundle does not intercept OutOfMemoryError (https://github.com/symfony/error-handler/blob/5.4/Error/OutOfMemoryError.php) when there is not enough memory.

@Baldinof
