### ISSUE TITLE
Scientific notation in Prometheus metrics

### ISSUE THREAD

**Issue by AndreyPoleshuk** [Baldinof/roadrunner-bundle#78]
Prometheus metrics with gauge type and value bigger than 100000 are exposed in the scientific notation like 1e+06. Is it possible somehow to manage it and expose it in simple number format as it is?

**Comment by Baldinof** [comment]
Hi, I think we cannot do anything here, this bundle simply *declare* metrics using RoadRunner API (sending metrics is up to RR).

Maybe have a try on the RoadRunner repo but there is big chances that there are just using the golang prometheus library.
