### ISSUE TITLE
Update symfony/psr-http-message-bridge dependency

### ISSUE THREAD

**Issue by vidurb** [Baldinof/roadrunner-bundle#8]
Hi Baldinof, I ran into a dependency conflict while trying to use your bundle from its dependency on v1.2 of `symfony/psr-http-message-bridge`. I looked at the changelog for that package and this one's source and I didn't see anything that would break (although of course I might be wrong about that). Are you working on updating that dependency, or is it OK if I submit a PR to do so? 

Thanks,
Vidur

**Comment by Baldinof** [comment]
Hi, thanks for opening this issue!

Release 1.2.1 now requires `"symfony/psr-http-message-bridge": "^1.1 || ^2.0"`. Does it fix your issue?

**Comment by vidurb** [comment]
Yes, working great so far. Thanks for your speedy comment and update! Most kind of you.
