### ISSUE TITLE
goridge_frame_receive: CRC verification failed, bad header: RuntimeExcep

### ISSUE THREAD

**Issue by hamdallah90** [Baldinof/roadrunner-bundle#81]
Hello, 

I have an issue while running this package

[INFO] RoadRunner server started; version: 2.9.1, buildtime: 2022-04-11T10:26:46+0000
2022-04-14T00:53:10.206Z	ERROR	container/poller.go:16	vertex got an error	{"id": "http.Plugin", "error": "static_pool_allocate_workers: WorkerAllocate:\n\tgoridge_frame_receive: CRC verification failed, bad header: <!DOCTYPE html>\n<html>\n    <head>\n        <meta "}
github.com/roadrunner-server/endure/pkg/container.(*Endure).poll.func1
	github.com/roadrunner-server/endure@v1.2.3/pkg/container/poller.go:16
error occurred: static_pool_allocate_workers: WorkerAllocate:
	goridge_frame_receive: CRC verification failed, bad header: <!DOCTYPE html>
<html>
    <head>
        <meta , plugin: http.Plugin
handle_serve_command: WorkerAllocate:
	static_pool_allocate_workers:
	goridge_frame_receive: CRC verification failed, bad header: <!DOCTYPE html>
<html>
    <head>
        <meta

I don't know what is the problem or what is missing.

Thanks

**Comment by piotrkardasz** [comment]
Hello 👋 
I had the same issue. Do you have a `symfony/runtime` installed and enabled in composer.json? 🤔 
And your `public/index.php` look like this: 
```php
<?php

use App\Kernel;

require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

return function (array $context) {
    return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
};
```

**Comment by Baldinof** [comment]
Hello!

I cannot reproduce with a fresh installation. What is your version of symfony and roadrunner-bundle ?

Did you try @piotrkardasz solution?

**Comment by hamdallah90** [comment]
worked thanks @piotrkardasz <3
