### ISSUE TITLE
symfony/messenger integration

### ISSUE THREAD

**Issue by Aleksa1996** [Baldinof/roadrunner-bundle#86]
Hello,

Thanks for this amazing bundle. I would like to ask if this bundle will get support for `symfony/messenger` component publisher side? 

Ive been playing with the bundle and after some time messenger throws error on publish: `Library error: a socket error occurred`. 

I think that rr keeps connection open with the transport (RabbitMQ). After some time transport (RabbitMQ) somehow terminates that connection,  but messenger component does not realize that and tries to publish message causing the above mentioned error.

**Comment by Baldinof** [comment]
Hello!

Thank you for the kind words :)

Messenger should work as expected, there is not much we can do on the bundle side.

It's an issue with the Symfony transport which fail to reconnect, see https://github.com/symfony/symfony/issues/42825

You can find some workarounds in the issue.

**Comment by Aleksa1996** [comment]
Okay, ill look into that. Thanks for the fast reply!

**Comment by Baldinof** [comment]
You're welcome, reach out if you have any other questions :)

**Comment by Aleksa1996** [comment]
If someone else has the same problem here is the solution i've stumbled across symfony/symfony#47091
